baseURL = "https://dsoniran.netlify.app" # to be updated once fully live "http://dsoniran.info"
languageCode = "en-us"
title = "darewithdata"
theme = "ananke"
# resourceDir = "../resources"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
disqusShortname = 'darewithdata'

[permalinks]
  posts = '/:year/:month/:slug/'

[languages]
  [languages.en]
    # title = "darewithdata"
    languageDirection = 'ltr' # for Right-To-Left languages
    weight = 1
    contentDir = "content/en"
    language_name = "English"
    [languages.en.menu]
      [[languages.en.menu.main]]
      name = 'Tags'
      pageref = '/tags'
      weight = 1
      
  [languages.fr]
    # title = "darewithdata"
    languageDirection = 'rtl'
    weight = 2
    contentDir = "content/fr"
    languageName = "French"
    [[languages.fr.menu.main]]
      name = 'étiqs'
      pageref  = '/tags'
      weight = 1

#[sitemap]
 # changefreq = "monthly"
  #priority = 0.5
  #filename = "sitemap.xml"

[params]
  body_classes = "alef bg-solarized"
  custom_css = ["meir.css", "jquery.bxslider.css"]
  text_color = "fg-solarized"
  author = ""
  favicon = "static/favicon.ico"
  site_logo = "img/logo.svg"
  # description = "The last theme you'll ever need. Maybe." unsure what this is for
  
  post_content_classes = "en"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-alt-background"
  recent_posts_number = 5
  # enable comments with disqus
  commentoEnable = true

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/dsoniran"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/darewithdata"
label = "TND Twitter"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/dsoniran"
label = "TND GitHub Account"
color = "#ff6800"

[[params.ananke_socials]]
name = "tableau"
url = "https://public.tableau.com/en-gb/s/"
label = "TND Tableau Public"
color = ""

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss"
    baseName = "feed"

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["rss"]


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'solarized-dark'
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
      block = true
    [markup.goldmark.renderer]
      unsafe = true
